version: 2.1

# yaml basic and advance: https://circleci.com/docs/2.0/writing-yaml/#section=configuration

# sharing data between jobs: https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs

base_environment: &base_environment
  IMAGE_NAME: shaungc/appl-tracky-api
  DEPLOYED_DOMAIN_NAME: appl-tracky.api.shaungc.com

# doc: https://circleci.com/orbs/registry/orb/circleci/slack
orbs:
  slack: circleci/slack@3.3.0

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      <<: *base_environment
    working_directory: ~/app
    steps:
      - checkout # retrieves the code from GitHub
      - setup_remote_docker # sets up a remote, isolated environment for each build. This is required before you use any docker command inside a job step.
      - run:
          name: Build Docker image
          command: |
            docker build -f django/Dockerfile -t $IMAGE_NAME:latest django
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1
  report_build:
    docker:
      - image: circleci/buildpack-deps:curl
    steps:
      - slack/status:
          mentions: 'here,'
          success_message: "*Build success - Appl Tracky API*\nAppl Tracky API build is ready.\nHash: ${CIRCLE_SHA1}"
  deploy:
    docker:
      - image: shaungc/terraform-kubectl-image
    environment:
      <<: *base_environment
    working_directory: ~/repo/cicd
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Run Terraform
          command: |
            ls -l
            chmod +x run-terraform.sh
            . ./run-terraform.sh
  report:
    docker:
      - image: circleci/buildpack-deps:curl
    environment:
      <<: *base_environment
    steps:
      - slack/status:
          mentions: 'here,'
          success_message: "*Published - Appl Tracky*\nAppl Tracky is ready to be accessed (https://${DEPLOYED_DOMAIN_NAME}).\nHash: ${CIRCLE_SHA1}\nDjango health check (https://${DEPLOYED_DOMAIN_NAME}/django-health-check/).\nDjango fail test (https://${DEPLOYED_DOMAIN_NAME}/fail-test/).\nDjango admin portal (https://${DEPLOYED_DOMAIN_NAME}/admin/)."


# circleci doc: https://circleci.com/docs/2.0/workflows/#fan-outfan-in-workflow-example
workflows:
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - report_build:
          requires:
            - build
      - deploy:
          requires:
            - report_build
      - report:
          requires:
            - deploy